### ISSUE TITLE
Compiler is out of heap space on npm install

### ISSUE THREAD

**Issue by andymartinwork** [atom/node-nslog#16]
I've never seen an error like this before. This happens on a windows 8 machine. Seems to work on my Windows 10 machine without problem.

I have found a similar problem with the nan module here: https://github.com/TooTallNate/node-weak/issues/74

```
npm install nslog@3.0.0

> nslog@3.0.0 install C:\Users\wimp\bamboo-agent-home\xml-data\build-dir\DESKTOP-EL-JOB1\node_modules\nslog
> node-gyp rebuild

C:\Users\wimp\bamboo-agent-home\xml-data\build-dir\DESKTOP-EL-JOB1\node_modules\nslog>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild)  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  main.cc
  nslog_win.cc
C:\Users\wimp\bamboo-agent-home\xml-data\build-dir\DESKTOP-EL-JOB1\node_modules\nan\nan.h(72): fatal error C1060: compiler is out of heap space (..\src\main.cc) [C:\Users\wimp\bamboo-agent-home\xml-data\build-dir\DESKTOP-EL-JOB1\node_modules\nslog\build\nslog.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\wimp\bamboo-agent-home\xml-data\build-dir\DESKTOP-EL-JOB1\node_modules\nslog
gyp ERR! node -v v6.3.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok

```

**Comment by andymartinwork** [comment]
I was able to get this module installing by adding a flag on the end:

`npm install nslog@3.0.0 --msvs_version=2013`
 
Perhaps this module should run like this by default? I have three separate versions of visual studio on my box (for legitimate reasons) and I guess this module only works with the 2013 VC++?
