### ISSUE TITLE
2.0.0 fails to build on windows

### ISSUE THREAD

**Issue by justinmchase** [atom/node-nslog#6]
Here is the log when I try to build. This is blocking me from installing `electron-rebuild`:

What versions of things do I need to have installed for this to work?

```
$ npm install nslog@2.0.0 -g
/
> nslog@2.0.0 install C:\Users\justin\AppData\Roaming\npm\node_modules\nslog
> node-gyp rebuild


C:\Users\justin\AppData\Roaming\npm\node_modules\nslog>if not defined npm_config_node_gyp (node "c:\Program Files\iojs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Warning: Missing input files:
c:\Users\justin\AppData\Roaming\npm\node_modules\nslog\build\Program Files\iojs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  main.cc
  nslog_win.cc
C:\Users\justin\.node-gyp\2.2.1\deps\v8\include\v8.h(3949): error C2332: 'enum' : missing tag name [C:\Users\justin\AppData\Roaming\npm\node_modules\nslog\build\nslog.vcxproj]
C:\Users\justin\.node-gyp\2.2.1\deps\v8\include\v8.h(3949): error C2236: unexpected 'class' 'v8::PropertyHandlerFlags'. Did you forget a ';'? [C:\Users\justin\AppData\Roaming\npm\node_modules\nslog\build\nslog.vcxproj]
C:\Users\justin\.node-gyp\2.2.1\deps\v8\include\v8.h(3949): error C3381: 'v8::PropertyHandlerFlags' : assembly access specifiers are only available in code compiled with a /clr option [C:\Users\justin\AppData\Roaming\npm\node_modules\nsl og\build\nslog.vcxproj]
C:\Users\justin\.node-gyp\2.2.1\deps\v8\include\v8.h(3949): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [C:\Users\justin\AppData\Roaming\npm\node_modules\nslog\build\nslog.vcxproj]
C:\Users\justin\.node-gyp\2.2.1\deps\v8\include\v8.h(3949): error C2864: 'v8::PropertyHandlerFlags::kNone' : only static const integral data members can be initialized within a class [C:\Users\justin\AppData\Roaming\npm\node_modules\nslo g\build\nslog.vcxproj]
C:\Users\justin\.node-gyp\2.2.1\deps\v8\include\v8.h(3949): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [C:\Users\justin\AppData\Roaming\npm\node_modules\nslog\build\nslog.vcxproj]
C:\Users\justin\.node-gyp\2.2.1\deps\v8\include\v8.h(3949): error C2864: 'v8::PropertyHandlerFlags::kAllCanRead' : only static const integral data members can be initialized within a class [C:\Users\justin\AppData\Roaming\npm\node_module s\nslog\build\nslog.vcxproj]
C:\Users\justin\.node-gyp\2.2.1\deps\v8\include\v8.h(3949): error C2143: syntax error : missing ';' before '}' [C:\Users\justin\AppData\Roaming\npm\node_modules\nslog\build\nslog.vcxproj]
C:\Users\justin\.node-gyp\2.2.1\deps\v8\include\v8.h(3953): error C2039: 'kNone' : is not a member of 'v8::PropertyHandlerFlags' [C:\Users\justin\AppData\Roaming\npm\node_modules\nslog\build\nslog.vcxproj]
          C:\Users\justin\.node-gyp\2.2.1\deps\v8\include\v8.h(3949) : see declaration of 'v8::PropertyHandlerFlags'
C:\Users\justin\.node-gyp\2.2.1\deps\v8\include\v8.h(3953): error C2039: 'kNone' : is not a member of 'v8::PropertyHandlerFlags' [C:\Users\justin\AppData\Roaming\npm\node_modules\nslog\build\nslog.vcxproj]
          C:\Users\justin\.node-gyp\2.2.1\deps\v8\include\v8.h(3949) : see declaration of 'v8::PropertyHandlerFlags'
C:\Users\justin\.node-gyp\2.2.1\deps\v8\include\v8.h(3981): error C2039: 'kNone' : is not a member of 'v8::PropertyHandlerFlags' [C:\Users\justin\AppData\Roaming\npm\node_modules\nslog\build\nslog.vcxproj]
          C:\Users\justin\.node-gyp\2.2.1\deps\v8\include\v8.h(3949) : see declaration of 'v8::PropertyHandlerFlags'
C:\Users\justin\.node-gyp\2.2.1\deps\v8\include\v8.h(3981): error C2039: 'kNone' : is not a member of 'v8::PropertyHandlerFlags' [C:\Users\justin\AppData\Roaming\npm\node_modules\nslog\build\nslog.vcxproj]
          C:\Users\justin\.node-gyp\2.2.1\deps\v8\include\v8.h(3949) : see declaration of 'v8::PropertyHandlerFlags'
C:\Users\justin\.node-gyp\2.2.1\deps\v8\include\v8.h(3981): error C2065: 'kNone' : undeclared identifier [C:\Users\justin\AppData\Roaming\npm\node_modules\nslog\build\nslog.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\Program Files\iojs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:199:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "c:\\Program Files\\iojs\\node.exe" "c:\\Program Files\\iojs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\justin\AppData\Roaming\npm\node_modules\nslog
gyp ERR! node -v v2.2.1
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "c:\\Program Files\\iojs\\node.exe" "c:\\Program Files\\iojs\\node_modules\\npm\\bin\\npm-cli.js" "install" "nslog@2.0.0" "-g"
npm ERR! node v2.2.1
npm ERR! npm  v2.11.0
npm ERR! code ELIFECYCLE

npm ERR! nslog@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nslog@2.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the nslog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls nslog
npm ERR! There is likely additional logging output above.
```

**Comment by justinmchase** [comment]
Actually it seems like it's just not compatible with iojs `2.2.1`, I installed `2.3.0` and now its building fine. You may want to add an `"engine": ">=2.3.0"` entry into package.json.
